// <auto-generated/>
#nullable enable
using System;
using Shouldly;
using Xunit;
using CodeToNeo4j.Extensions;
using CodeToNeo4j.Neo4j;

namespace CodeToNeo4j.Tests.Extensions;

public class StringExtensionsTests {
	[Fact]
	public void Truncate_NullInput_ReturnsNull() {
		string? input = null;
		var result = input.Truncate();
		Assert.Null(result);
	}

	[Fact]
	public void Truncate_EmptyString_ReturnsEmpty() {
		string input = "";
		var result = input.Truncate();
		Assert.Equal(string.Empty, result);
	}

	[Fact]
	public void Truncate_StringShorterThanMax_ReturnsOriginal() {
		string input = "test";
		var result = input.Truncate();
		Assert.Equal(input, result);
	}

	[Fact]
	public void Truncate_StringLongerThanMax_Truncates() {
		string input = new string('x', 9000);
		var result = input.Truncate();
		result.ShouldNotBeNull();
		result.Length.ShouldBe(8000);
	}

	[Fact]
	public void GivenNull_WhenTruncate_ThenReturnsNull()
	{
		default(string)!.Truncate().ShouldBeNull();
	}

	[Theory]
	[InlineData("")]
	[InlineData("short")]
	public void GivenShortString_WhenTruncate_ThenReturnsUnchanged(string input)
	{
		input.Truncate().ShouldBe(input);
	}

	[Fact]
	public void GivenExactlyMaxLength_WhenTruncate_ThenReturnsUnchanged()
	{
		var input = new string('x', Neo4jFlushService.MaxIndexedStringLength);
		input.Truncate().ShouldBe(input);
	}

	[Fact]
	public void GivenOverMaxLength_WhenTruncate_ThenTruncatesToMaxLength()
	{
		var input = new string('x', Neo4jFlushService.MaxIndexedStringLength + 500);

		var result = input.Truncate();

		result!.Length.ShouldBe(Neo4jFlushService.MaxIndexedStringLength);
	}
}
