name: PR Requirements

on:
  pull_request:
    types: [ opened, labeled, unlabeled, synchronize, reopened, edited ]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  create-and-link-issue:
    name: Create issue and update PR body
    if: contains(github.event.pull_request.labels.*.name, 'renovate')
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1
          clean: true

      - name: Create issue and update PR body
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          retries: 3
          script: |
            const script = require('./.github/scripts/pr-requirements_create-and-link-issue.js')
            await script({github, context, core})

  check-label:
    name: Check for at least one label
    runs-on: self-hosted
    steps:
      - name: Check for at least one label
        env:
          LABELS: ${{ toJson(github.event.pull_request.labels) }}
        run: ./.github/scripts/pr-requirements_check-label.sh

  check-issue-reference:
    name: Check for issue reference in PR body
    needs: [ create-and-link-issue ]
    if: always() && !cancelled()
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1
          clean: true

      - name: Check for issue number in Resolves field
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: ./.github/scripts/pr-requirements_check-issue-reference.sh

  check-tests-checkbox:
    name: Check that tests checkbox is checked
    runs-on: self-hosted
    steps:
      - name: Check that tests checkbox is checked
        env:
          BODY: ${{ github.event.pull_request.body }}
          LABELS: ${{ toJson(github.event.pull_request.labels) }}
          SENDER: ${{ github.event.pull_request.user.login }}
        run: ./.github/scripts/pr-requirements_check-tests-checkbox.sh

  check-rebased-checkbox:
    name: Check that rebased checkbox is checked
    runs-on: self-hosted
    steps:
      - name: Check that rebased checkbox is checked
        env:
          BODY: ${{ github.event.pull_request.body }}
          SENDER: ${{ github.event.pull_request.user.login }}
        run: ./.github/scripts/pr-requirements_check-rebased-checkbox.sh
