name: Verify Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
        clean: false

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore -c Release

    - name: Test
      run: dotnet test --no-build -c Release --verbosity normal